# Generated by Django 4.1.5 on 2023-01-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_plot', models.ImageField(upload_to='demand', verbose_name='График зарплат')),
                ('count_plot', models.ImageField(upload_to='demand', verbose_name='График количества вакансий')),
                ('table_html', models.TextField(verbose_name='HTML-код таблицы')),
            ],
            options={
                'verbose_name': 'Страница востребованности',
                'verbose_name_plural': 'Экземляры страниц востребованности',
            },
        ),
        migrations.CreateModel(
            name='GeographyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_name', models.CharField(max_length=128, verbose_name='Название вакансии')),
                ('profession_plot', models.ImageField(upload_to='geography', verbose_name='График по указанной вакансии')),
                ('profession_salary_html', models.TextField(verbose_name='HTML-код таблицы зарплат по указанной вакансиям')),
                ('profession_share_html', models.TextField(verbose_name='HTML-код таблицы долей по указанной вакансиям')),
                ('it_plot', models.ImageField(upload_to='geography', verbose_name='График по IT-вакансиям')),
                ('it_salary_html', models.TextField(verbose_name='HTML-код таблицы зарплат по IT-вакансиям')),
                ('it_share_html', models.TextField(verbose_name='HTML-код таблицы долей по IT-вакансиям')),
            ],
            options={
                'verbose_name': 'Страница географии',
                'verbose_name_plural': 'Экземляры страниц географии',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home', verbose_name='Изображение')),
                ('text_before_image', models.TextField(verbose_name='HTML-код до изображения')),
                ('text_after_image', models.TextField(verbose_name='HTML-код после изображения')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Экземляры главных страниц',
            },
        ),
        migrations.CreateModel(
            name='SkillYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('plot', models.ImageField(upload_to='skills', verbose_name='График за год')),
                ('table_html', models.TextField(verbose_name='HTML-код таблицы')),
            ],
            options={
                'verbose_name': 'Статистика навыков за год',
                'verbose_name_plural': 'Статистики навыков за год',
            },
        ),
        migrations.CreateModel(
            name='VacancyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=256, verbose_name='Поисковый запрос')),
                ('count', models.IntegerField(verbose_name='Количество вакансий')),
            ],
            options={
                'verbose_name': 'Страница вакансий',
                'verbose_name_plural': 'Экземляры страниц вакансий',
            },
        ),
    ]
